site_name: My Docs

theme:
  name: material

nav:
  - Home: index.md
  - Założenia Projektowe: wymagania_projektowe.md
  - Poetry Usage Tutorial: POETRY.md
  - Yearly Data Description: yearly_data.md
  - Project Report: project_report.md
